#!/usr/bin/env python3
"""Add an approved GitHub member application to team.html.

The script accepts the Issue Form body through ISSUE_BODY and the issue number
through ISSUE_NUMBER. All user-controlled values are validated and HTML-escaped
before a card is inserted at one of the AUTO-MEMBERS markers.
"""

from __future__ import annotations

import argparse
import html
import os
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit


SECTION_BY_ROLE = {
    "教师": "FACULTY",
    "博士研究生": "GRADUATE",
    "硕士研究生": "GRADUATE",
    "本科生": "UNDERGRADUATE",
}

NO_RESPONSE_VALUES = {"", "_No response_", "无", "不提供", "N/A", "n/a"}
GITHUB_IMAGE_HOSTS = {"github.com", "user-images.githubusercontent.com"}


class SubmissionError(ValueError):
    """Raised when an application cannot be safely published."""


def parse_issue_form(body: str) -> dict[str, str]:
    """Parse the Markdown headings generated by a GitHub Issue Form."""
    body = body.replace("\r\n", "\n")
    headings = list(re.finditer(r"^###\s+(.+?)\s*$", body, flags=re.MULTILINE))
    fields: dict[str, str] = {}

    for index, match in enumerate(headings):
        start = match.end()
        end = headings[index + 1].start() if index + 1 < len(headings) else len(body)
        label = match.group(1).strip()
        fields[label] = body[start:end].strip()

    return fields


def required(fields: dict[str, str], label: str) -> str:
    value = fields.get(label, "").strip()
    if value in NO_RESPONSE_VALUES:
        raise SubmissionError(f"缺少必填字段：{label}")
    return value


def optional(fields: dict[str, str], label: str) -> str:
    value = fields.get(label, "").strip()
    return "" if value in NO_RESPONSE_VALUES else value


def compact_text(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def validate_text(value: str, label: str, minimum: int, maximum: int) -> str:
    value = compact_text(value)
    if not minimum <= len(value) <= maximum:
        raise SubmissionError(f"{label}长度应为 {minimum}–{maximum} 个字符")
    if any(ord(character) < 32 for character in value):
        raise SubmissionError(f"{label}包含不可见控制字符")
    return value


def validate_url(value: str, label: str, allowed_hosts: set[str] | None = None) -> str:
    if not value:
        return ""

    value = compact_text(value)
    parsed = urlsplit(value)
    hostname = (parsed.hostname or "").lower()
    if parsed.scheme not in {"http", "https"} or not hostname:
        raise SubmissionError(f"{label}必须是完整的 http 或 https 地址")
    if parsed.username or parsed.password:
        raise SubmissionError(f"{label}不能包含账号或密码")
    if allowed_hosts and hostname not in allowed_hosts:
        allowed = "、".join(sorted(allowed_hosts))
        raise SubmissionError(f"{label}必须来自：{allowed}")
    if len(value) > 500:
        raise SubmissionError(f"{label}地址过长")
    return value


def validate_email(value: str) -> str:
    if not value:
        return ""

    value = compact_text(value)
    if len(value) > 254 or not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", value):
        raise SubmissionError("公开邮箱格式不正确")
    return value


def extract_photo_url(value: str) -> str:
    candidates = []
    candidates.extend(re.findall(r"!\[[^\]]*\]\((https://[^\s)]+)", value))
    candidates.extend(re.findall(r"<img[^>]+src=[\"'](https://[^\"']+)[\"']", value, flags=re.I))
    candidates.extend(re.findall(r"https://[^\s)>\"']+", value))

    for candidate in candidates:
        candidate = html.unescape(candidate.rstrip(".,;，。；"))
        parsed = urlsplit(candidate)
        hostname = (parsed.hostname or "").lower()
        is_github_attachment = hostname == "github.com" and parsed.path.startswith("/user-attachments/assets/")
        is_legacy_attachment = hostname == "user-images.githubusercontent.com"
        if parsed.scheme == "https" and (is_github_attachment or is_legacy_attachment):
            return candidate

    hosts = "、".join(sorted(GITHUB_IMAGE_HOSTS))
    raise SubmissionError(f"头像必须先上传到 GitHub（支持 {hosts} 的公开图片链接）")


def render_link(url: str, icon: str, label: str, external: bool = True) -> str:
    attributes = ' target="_blank" rel="noopener noreferrer"' if external else ""
    return (
        f'              <a href="{html.escape(url, quote=True)}"{attributes} '
        f'aria-label="{html.escape(label, quote=True)}"><i class="{icon}"></i></a>'
    )


def render_card(fields: dict[str, str], issue_number: int) -> tuple[str, str]:
    name = validate_text(required(fields, "姓名"), "姓名", 2, 40)
    role = compact_text(required(fields, "成员类别"))
    if role not in SECTION_BY_ROLE:
        supported = "、".join(SECTION_BY_ROLE)
        raise SubmissionError(f"不支持的成员类别：{role}；可选类别为 {supported}")

    bio = validate_text(required(fields, "个人简介"), "个人简介", 10, 800)
    photo = extract_photo_url(required(fields, "头像"))
    email = validate_email(optional(fields, "公开邮箱"))
    homepage = validate_url(optional(fields, "个人主页"), "个人主页")
    github = validate_url(optional(fields, "GitHub 主页"), "GitHub 主页", {"github.com", "www.github.com"})
    scholar = validate_url(
        optional(fields, "Google Scholar"),
        "Google Scholar",
        {"scholar.google.com"},
    )

    card_class = "team-card faculty-card" if role == "教师" else "team-card"
    links = []
    if homepage:
        links.append(render_link(homepage, "fas fa-globe", f"{name}的个人主页"))
    if email:
        links.append(render_link(f"mailto:{email}", "fas fa-envelope", f"给{name}发送邮件", external=False))
    if scholar:
        links.append(render_link(scholar, "fab fa-google", f"{name}的Google Scholar"))
    if github:
        links.append(render_link(github, "fab fa-github", f"{name}的GitHub"))

    links_html = ""
    if links:
        links_html = "\n".join([
            '            <div class="member-links">',
            *links,
            "            </div>",
        ])

    escaped_name = html.escape(name)
    card_lines = [
        f'        <div class="{card_class}" data-member-issue="{issue_number}">',
        '          <div class="member-photo">',
        (
            f'            <img src="{html.escape(photo, quote=True)}" '
            f'alt="{html.escape(name, quote=True)}" loading="lazy">'
        ),
        "          </div>",
        '          <div class="member-info">',
        f"            <h3>{escaped_name}</h3>",
        f'            <div class="member-position">{html.escape(role)}</div>',
        '            <div class="member-short-bio">',
        f"              {html.escape(bio)}",
        "            </div>",
    ]
    if links_html:
        card_lines.append(links_html)
    card_lines.extend(["          </div>", "        </div>"])

    return SECTION_BY_ROLE[role], "\n".join(card_lines)


def update_team_file(team_file: Path, body: str, issue_number: int) -> bool:
    source = team_file.read_text(encoding="utf-8")
    issue_marker = f'data-member-issue="{issue_number}"'
    if issue_marker in source:
        print(f"申请 #{issue_number} 已存在于 {team_file}，无需重复添加。")
        return False

    section, card = render_card(parse_issue_form(body), issue_number)
    marker = f"        <!-- AUTO-MEMBERS:{section} -->"
    if source.count(marker) != 1:
        raise SubmissionError(f"团队页面缺少唯一插入标记：{marker.strip()}")

    updated = source.replace(marker, f"{card}\n\n{marker}", 1)
    team_file.write_text(updated, encoding="utf-8")
    print(f"已将申请 #{issue_number} 添加到 {section} 区域。")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--team-file", type=Path, default=Path("team.html"))
    parser.add_argument("--issue-number", type=int, default=int(os.environ.get("ISSUE_NUMBER", "0")))
    parser.add_argument("--body-file", type=Path, help="本地测试时从文件读取 Issue 正文")
    args = parser.parse_args()

    if args.issue_number <= 0:
        print("错误：ISSUE_NUMBER 必须是正整数。", file=sys.stderr)
        return 2

    body = args.body_file.read_text(encoding="utf-8") if args.body_file else os.environ.get("ISSUE_BODY", "")
    if not body.strip():
        print("错误：未提供 Issue Form 正文。", file=sys.stderr)
        return 2

    try:
        update_team_file(args.team_file, body, args.issue_number)
    except (OSError, SubmissionError) as error:
        print(f"错误：{error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
